### ISSUE TITLE
Unhandled exception. System.ArgumentException: Value does not fall within the expected range

### ISSUE THREAD

**Issue by btrentini** [raysworld/Xef2Mat#5]
Hello,
I am trying to execute the code using Visual Studio 2019. As far as I know, no dependencies (Kinect SDK 2.0 installed)

This is the full error when I execute it through Power Shell Command line after "Build" using Visual Studio.

```
**********************************************************************
** Visual Studio 2019 Developer PowerShell v16.6.3
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
PS C:\Users\bruno\source\repos> cd C:\Users\bruno\source\repos\Xef2Mat\binary
PS C:\Users\bruno\source\repos\Xef2Mat\binary> .\Xef2Mat.exe --no-gui .\016_jeep_other_fluids.xef
PS C:\Users\bruno\source\repos\Xef2Mat\binary> [INFO] An output folder is not specified. Use default value.
[INFO] Input File: .\016_jeep_other_fluids.xef
[INFO] Output Folder: C:\Users\bruno\source\repos\Xef2Mat\binary/output
Unhandled exception. System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Kinect.Tools.ExceptionHelper.ThrowOnFail(Int32& hr)
   at Microsoft.Kinect.Tools.KStudioClient.OpenEventFile(String filePath, KStudioEventFileFlags fileFlags)
   at XEF2MATCore.Xef2MatCore.Load(String path, String out_path)
   at XEF2MAT_UI.App.ConsoleLoad(String[] args)
   at XEF2MAT_UI.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at XEF2MAT_UI.App.Main()
```
If I choose Debug on visual studio, I get this error:

![image](https://user-images.githubusercontent.com/16156013/87395776-cb596600-c5a9-11ea-9697-8e77457ef86b.png)

The GUI simply doesn't work (never leaves the "Ready" message after choosing the file)

Thanks a lot for your help in advance!

**Comment by raysworld** [comment]
Hi, btrentini,

It has been a while I did not handle this repo... Would it be possible for you to send the .xef file to me to check what is going wrong with the code?

BR,

Rui

**Comment by raysworld** [comment]
> If I choose Debug on visual studio, I get this error:
> 
> ![image](https://user-images.githubusercontent.com/16156013/87395776-cb596600-c5a9-11ea-9697-8e77457ef86b.png)
> 
> The GUI simply doesn't work (never leaves the "Ready" message after choosing the file)

To solve this problem, right click on ''XEF2MAT_UI" and set it as a startup project
![Annotation 2020-07-20 102218](https://user-images.githubusercontent.com/8063827/87893580-e9740a00-ca72-11ea-98a6-5db64aaa69e2.png)
